apiVersion: apps/v1
kind: Deployment
metadata:
  name: issue-management-service
  labels:
    app: issue-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: issue-management-service

  template:
    metadata:
      labels:
        app: issue-management-service
    spec:
      containers:
        - name: issue-management-service
          image: gcr.io/cc-assignment-01-407011/issue-management-service:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "300m"
              memory: "400Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"